### ISSUE TITLE
Coloration du chat

### ISSUE THREAD

**Issue by DevelopHeureShell** [DigitalPulseSoftware/BurgWar#16]
Il serait utile de colorer les messages envoyés par les joueurs dans le chat en une couleur (par exemple le rouge, bien que cela soit un peu agressif pour les yeux), les faisant ressortir. Éventuellement, la taille des caractères de ces messages pourrait être augmentée.

**Comment by DrLynix** [comment]
Fait. J'ai augmenté légèrement la taille des caractère et ajouté de la coloration, voilà à quoi ressemble maintenant le chat:
![](https://user-images.githubusercontent.com/3002461/71542776-bfd68280-296a-11ea-8716-334dbb82bbf5.png)
